services:
  wg:
    build: .
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

    env_file:
      - .env

    secrets:
      - session.key

    logging:
      driver: json-file
      options:
        max-size: 50m

    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
      - ./secret:/run/secrets

secrets:
  session.key:
    file: ./secret/session.key
